import { CreateLetterDto } from './letters/create-letter.dto';
import { CreateCombinationDto } from './combinations/create-combination.dto';
import { CreateSyllableDto } from './syllables/create-syllable.dto';
import { CreateSimilarLetterDto } from './similar-letters/create-similar-letter.dto';
import { CreateWordDto } from './words/create-word.dto';
import { CreateCourseDto } from '../courses/create-course.dto';
import { CreateCoordinateDto } from './coordinates/create-coordinate.dto';

export const similarLettersList: CreateSimilarLetterDto[] = [
  {
    letter: 'a',
    similarLetters: ['k', 'g', 'd', 'o', 'b', 'p', 'q'],
  },
  {
    letter: 'b',
    similarLetters: ['r', 'd', 'p', 'q', 'g', 'c', 'v'],
  },
  {
    letter: 'c',
    similarLetters: ['m', 's', 'z', 'e', 'd', 'b', 'q'],
  },
  {
    letter: 'd',
    similarLetters: ['c', 'b', 'p', 'q', 'g', 'v', 'a'],
  },
  {
    letter: 'e',
    similarLetters: ['f', 'g', 'r', 'c', 'd', 'b', 'o'],
  },
  {
    letter: 'f',
    similarLetters: ['e', 't', 'r', 'd', 'l', 'i', 'h'],
  },
  {
    letter: 'g',
    similarLetters: ['b', 'a', 'p', 'q', 'o', 'r', 'c'],
  },
  {
    letter: 'h',
    similarLetters: ['r', 'ñ', 'n', 'm', 'd', 'u', 'b'],
  },
  {
    letter: 'i',
    similarLetters: ['k', 'j', 'l', 'y', 'r', 't', 'h'],
  },
  {
    letter: 'j',
    similarLetters: ['l', 'i', 'g', 'p', 'q', 'y', 't'],
  },
  {
    letter: 'k',
    similarLetters: ['y', 'c', 'q', 'p', 'r', 'x', 'a'],
  },
  {
    letter: 'l',
    similarLetters: ['b', 'i', 'j', 't', 'k', 'h', 'f'],
  },
  {
    letter: 'm',
    similarLetters: ['f', 'ñ', 'n', 'h', 'r', 'w', 'v'],
  },
  {
    letter: 'n',
    similarLetters: ['b', 'm', 'ñ', 'h', 'r', 'w', 'v'],
  },
  {
    letter: 'ñ',
    similarLetters: ['f', 'n', 'm', 'h', 'r', 'g', 'c'],
  },
  {
    letter: 'o',
    similarLetters: ['g', 'p', 'q', 'd', 'b', 'a', 'c'],
  },
  {
    letter: 'p',
    similarLetters: ['e', 'q', 'd', 'b', 'g', 'o', 'a'],
  },
  {
    letter: 'q',
    similarLetters: ['u', 'p', 'd', 'b', 'g', 'o', 'a'],
  },
  {
    letter: 'r',
    similarLetters: ['n', 'c', 'g', 'f', 't', 'a', 'y'],
  },
  {
    letter: 's',
    similarLetters: ['r', 'c', 'z', 'g', 'a', 'u', 'm'],
  },
  {
    letter: 't',
    similarLetters: ['e', 'f', 'l', 'i', 'r', 'y', 'h'],
  },
  {
    letter: 'u',
    similarLetters: ['n', 'o', 'q', 'p', 'v', 'w', 'c'],
  },
  {
    letter: 'v',
    similarLetters: ['n', 'e', 'u', 'y', 'x', 'a', 'w'],
  },
  {
    letter: 'w',
    similarLetters: ['n', 'v', 'u', 'y', 'x', 'z', 'm'],
  },
  {
    letter: 'x',
    similarLetters: ['e', 'v', 'w', 'y', 'z', 'k', 'c'],
  },
  {
    letter: 'y',
    similarLetters: ['d', 'i', 'v', 'g', 'x', 'k', 'q'],
  },
  {
    letter: 'z',
    similarLetters: ['f', 's', 'c', 'x', 'y', 'h', 'w'],
  },
  {
    letter: 'A',
    similarLetters: ['Y', 'V', 'W', 'X', 'N', 'K', 'M'],
  },
  {
    letter: 'B',
    similarLetters: ['D', 'E', 'F', 'S', 'G', 'P', 'R'],
  },
  {
    letter: 'C',
    similarLetters: ['T', 'S', 'Z', 'D', 'G', 'O', 'Q'],
  },
  {
    letter: 'D',
    similarLetters: ['B', 'O', 'Q', 'P', 'E', 'R', 'G'],
  },
  {
    letter: 'E',
    similarLetters: ['R', 'F', 'T', 'H', 'I', 'L', 'B'],
  },
  {
    letter: 'F',
    similarLetters: ['R', 'E', 'T', 'H', 'L', 'K', 'P'],
  },
  {
    letter: 'G',
    similarLetters: ['J', 'C', 'Q', 'O', 'P', 'U', 'D'],
  },
  {
    letter: 'H',
    similarLetters: ['K', 'I', 'T', 'L', 'E', 'F', 'B'],
  },
  {
    letter: 'I',
    similarLetters: ['Y', 'T', 'L', 'F', 'P', 'E', 'H'],
  },
  {
    letter: 'J',
    similarLetters: ['S', 'G', 'Y', 'T', 'L', 'I', 'U'],
  },
  {
    letter: 'K',
    similarLetters: ['A', 'Y', 'X', 'W', 'V', 'R', 'B'],
  },
  {
    letter: 'L',
    similarLetters: ['M', 'I', 'T', 'H', 'F', 'E', 'V'],
  },
  {
    letter: 'M',
    similarLetters: ['R', 'N', 'Ñ', 'W', 'V', 'Y', 'K'],
  },
  {
    letter: 'N',
    similarLetters: ['R', 'M', 'Ñ', 'W', 'V', 'Y', 'K'],
  },
  {
    letter: 'Ñ',
    similarLetters: ['R', 'M', 'N', 'W', 'V', 'Y', 'K'],
  },
  {
    letter: 'O',
    similarLetters: ['B', 'Q', 'G', 'D', 'C', 'U', 'R'],
  },
  {
    letter: 'P',
    similarLetters: ['E', 'R', 'Q', 'K', 'D', 'B', 'G'],
  },
  {
    letter: 'Q',
    similarLetters: ['U', 'G', 'O', 'C', 'D', 'B', 'R'],
  },
  {
    letter: 'R',
    similarLetters: ['L', 'P', 'K', 'B', 'D', 'F', 'E'],
  },
  {
    letter: 'S',
    similarLetters: ['M', 'C', 'Z', 'B', 'R', 'E', 'F'],
  },
  {
    letter: 'T',
    similarLetters: ['D', 'H', 'L', 'I', 'Y', 'Z', 'P'],
  },
  {
    letter: 'U',
    similarLetters: ['A', 'V', 'W', 'O', 'Q', 'P', 'N'],
  },
  {
    letter: 'V',
    similarLetters: ['Q', 'W', 'A', 'N', 'M', 'U', 'Ñ'],
  },
  {
    letter: 'W',
    similarLetters: ['A', 'M', 'V', 'U', 'K', 'X', 'N'],
  },
  {
    letter: 'X',
    similarLetters: ['E', 'K', 'Y', 'W', 'V', 'Z', 'A'],
  },
  {
    letter: 'Y',
    similarLetters: ['I', 'X', 'K', 'T', 'L', 'V', 'W'],
  },
  {
    letter: 'Z',
    similarLetters: ['N', 'S', 'C', 'R', 'K', 'Y', 'T'],
  },
];

export const combinationsList: CreateCombinationDto[] = [
  {
    letter: 'a',
    combinations: [
      {
        combination: 'aa',
        word:        'portaaviones',
        syllable:    { w: 'aa', p: 'aa' },
        syllables:   [ 'port', 'aa', 'viones' ],
      },
      {
        combination: 'ae',
        word:        'aeropuerto',
        syllable:    { w: 'ae', p: 'ae' },
        syllables:   [ 'ae', 'ropuerto' ],
      },
      {
        combination: 'ai',
        word:        'paisaje',
        syllable:    { w: 'ai', p: 'ai' },
        syllables:   [ 'p', 'ai', 'saje' ],
      },
      {
        combination: 'ao',
        word:        'karaoke',
        syllable:    { w: 'ao', p: 'ao' },
        syllables:   [ 'kar', 'ao', 'ke' ],
      },
      {
        combination: 'au',
        word:        'jaula',
        syllable:    { w: 'au', p: 'au' },
        syllables:   [ 'j', 'au', 'la' ],
      },
    ],
  },
  {
    letter: 'b',
    combinations: [
      {
        combination: 'ba',
        word:        'barco',
        syllable:    { w: 'ba', p: 'ba' },
        syllables:   ['ba', 'rco' ],
      },
      {
        combination: 'be',
        word:        'becerro',
        syllable:    { w: 'be', p: 've' },
        syllables:   [ 'be', 'cerro' ],
      },
      {
        combination: 'bi',
        word:        'bicicleta',
        syllable:    { w: 'bi', p: 'bi' },
        syllables:   [ 'bi', 'cicleta' ],
      },
      {
        combination: 'bo',
        word:        'bota',
        syllable:    { w: 'bo', p: 'bo' },
        syllables:   [ 'bo', 'ta' ],
      },
      {
        combination: 'bu',
        word:        'burro',
        syllable:    { w: 'bu', p: 'bu' },
        syllables:   [ 'bu', 'rro' ],
      },
    ],
  },
  {
    letter: 'c',
    combinations: [
      {
        combination: 'ca',
        word:        'casa',
        syllable:    { w: 'ca', p: 'ca' },
        syllables:   [ 'ca', 'sa' ],
      },
      {
        combination: 'ce',
        word:        'cebolla',
        syllable:    { w: 'ce', p: 'ce' },
        syllables:   [ 'ce', 'bolla' ],
      },
      {
        combination: 'ci',
        word:        'cine',
        syllable:    { w: 'ci', p: 'ci' },
        syllables:   [ 'ci', 'ne' ],
      },
      {
        combination: 'co',
        word:        'coco',
        syllable:    { w: 'co', p: 'co' },
        syllables:   [ 'co', 'co' ],
      },
      {
        combination: 'cu',
        word:        'cuna',
        syllable:    { w: 'cu', p: 'cu' },
        syllables:   [ 'cu', 'na' ],
      },
    ],
  },
  {
    letter: 'd',
    combinations: [
      {
        combination: 'da',
        word:        'dado',
        syllable:    { w: 'da', p: 'da' },
        syllables:   [ 'da', 'do' ],
      },
      {
        combination: 'de',
        word:        'dedo',
        syllable:    { w: 'de', p: 'de' },
        syllables:   [ 'de', 'do' ],
      },
      {
        combination: 'di',
        word:        'dinero',
        syllable:    { w: 'di', p: 'di' },
        syllables:   [ 'di', 'nero' ],
      },
      {
        combination: 'do',
        word:        'dona',
        syllable:    { w: 'do', p: 'do' },
        syllables:   [ 'do', 'na' ],
      },
      {
        combination: 'du',
        word:        'dulce',
        syllable:    { w: 'du', p: 'du' },
        syllables:   [ 'du', 'lce' ],
      },
    ],
  },
  {
    letter: 'e',
    combinations: [
      {
        combination: 'ea',
        word:        'aldea',
        syllable:    { w: 'ea', p: 'ea' },
        syllables:   [ 'ald', 'ea' ],
      },
      {
        combination: 'ee',
        word:        'leer',
        syllable:    { w: 'ee', p: 'ee' },
        syllables:   [ 'l', 'ee', 'r' ],
      },
      {
        combination: 'ei',
        word:        'aceite',
        syllable:    { w: 'ei', p: 'ei' },
        syllables:   [ 'ac', 'ei', 'te' ],
      },
      {
        combination: 'eo',
        word:        'fideo',
        syllable:    { w: 'eo', p: 'eo' },
        syllables:   [ 'fid', 'eo' ],
      },
      {
        combination: 'eu',
        word:        'reunión',
        syllable:    { w: 'eu', p: 'eu' },
        syllables:   [ 'r', 'eu', 'nión' ],
      },
    ],
  },
  {
    letter: 'f',
    combinations: [
      {
        combination: 'fa',
        word:        'faro',
        syllable:    { w: 'fa', p: 'fa' },
        syllables:   [ 'fa', 'ro' ],
      },
      {
        combination: 'fe',
        word:        'feliz',
        syllable:    { w: 'fe', p: 'fe' },
        syllables:   [ 'fe', 'liz' ],
      },
      {
        combination: 'fi',
        word:        'fiesta',
        syllable:    { w: 'fi', p: 'fi' },
        syllables:   [ 'fi', 'esta' ],
      },
      {
        combination: 'fo',
        word:        'foco',
        syllable:    { w: 'fo', p: 'fo' },
        syllables:   [ 'fo', 'co' ],
      },
      {
        combination: 'fu',
        word:        'fuego',
        syllable:    { w: 'fu', p: 'fu' },
        syllables:   [ 'fu', 'ego' ],
      },
    ],
  },
  {
    letter: 'g',
    combinations: [
      {
        combination: 'ga',
        word:        'gato',
        syllable:    { w: 'ga', p: 'ga' },
        syllables:   [ 'ga', 'to' ],
      },
      {
        combination: 'gue',
        word:        'guerrero',
        syllable:    { w: 'gue', p: 'gue' },
        syllables:   [ 'gue', 'rrero' ],
      },
      {
        combination: 'gui',
        word:        'guitarra',
        syllable:    { w: 'gui', p: 'gui' },
        syllables:   [ 'gui', 'tarra' ],
      },
      {
        combination: 'go',
        word:        'gorra',
        syllable:    { w: 'go', p: 'go' },
        syllables:   [ 'go', 'rra' ],
      },
      {
        combination: 'gu',
        word:        'gusano',
        syllable:    { w: 'gu', p: 'gu' },
        syllables:   [ 'gu', 'sano' ],
      },
      {
        combination: 'ge',
        word:        'gelatina',
        syllable:    { w: 'ge', p: 'ge' },
        syllables:   [ 'ge', 'latina' ],
      },
      {
        combination: 'gi',
        word:        'girasol',
        syllable:    { w: 'gi', p: 'ji' },
        syllables:   [ 'gi', 'rasol' ],
      },
      {
        combination: 'gua',
        word:        'agua',
        syllable:    { w: 'gua', p: 'gua' },
        syllables:   [ 'a', 'gua' ],
      },
      {
        combination: 'güe',
        word:        'cigüeñas',
        syllable:    { w: 'güe', p: 'güe' },
        syllables:   [ 'ci', 'güe', 'ña' ],
      },
      {
        combination: 'güi',
        word:        'pingüino',
        syllable:    { w: 'güi', p: 'güi' },
        syllables:   [ 'pin', 'güi', 'no' ],
      },
      {
        combination: 'guo',
        word:        'antiguo',
        syllable:    { w: 'guo', p: 'guo' },
        syllables:   [ 'anti', 'guo' ],
      },
    ],
  },
  {
    letter: 'h',
    combinations: [
      {
        combination: 'ha',
        word:        'hacha',
        syllable:    { w: 'ha', p: 'a' },
        syllables:   [ 'ha', 'cha' ],
      },
      {
        combination: 'he',
        word:        'helado',
        syllable:    { w: 'he', p: 'e' },
        syllables:   [ 'he', 'la', 'do' ],
      },
      {
        combination: 'hi',
        word:        'hilo',
        syllable:    { w: 'hi', p: 'i' },
        syllables:   [ 'hi', 'lo' ],
      },
      {
        combination: 'ho',
        word:        'horno',
        syllable:    { w: 'ho', p: 'o' },
        syllables:   [ 'ho', 'rno' ],
      },
      {
        combination: 'hu',
        word:        'hueso',
        syllable:    { w: 'hu', p: 'u' },
        syllables:   [ 'hu', 'eso' ],
      },
    ],
  },
  {
    letter: 'i',
    combinations: [
      {
        combination: 'ia',
        word:        'familia',
        syllable:    { w: 'ia', p: 'ia' },
        syllables:   [ 'famil', 'ia' ],
      },
      {
        combination: 'ie',
        word:        'pie',
        syllable:    { w: 'ie', p: 'ie' },
        syllables:   [ 'p', 'ie' ],
      },
      {
        combination: 'ii',
        word:        'hawaii',
        syllable:    { w: 'ii', p: 'ii' },
        syllables:   [ 'hawa', 'ii' ],
      },
      {
        combination: 'io',
        word:        'apio',
        syllable:    { w: 'io', p: 'io' },
        syllables:   [ 'ap', 'io' ],
      },
      {
        combination: 'iu',
        word:        'ciudad',
        syllable:    { w: 'iu', p: 'iu' },
        syllables:   [ 'c', 'iu', 'dad' ],
      },
    ],
  },
  {
    letter: 'j',
    combinations: [
      {
        combination: 'ja',
        word:        'jaula',
        syllable:    { w: 'ja', p: 'ja' },
        syllables:   [ 'ja', 'ula' ],
      },
      {
        combination: 'je',
        word:        'jefe',
        syllable:    { w: 'je', p: 'ge' },
        syllables:   [ 'je', 'fe' ],
      },
      {
        combination: 'ji',
        word:        'jirafa',
        syllable:    { w: 'ji', p: 'ji' },
        syllables:   [ 'ji', 'rafa' ],
      },
      {
        combination: 'jo',
        word:        'joya',
        syllable:    { w: 'jo', p: 'ho' },
        syllables:   [ 'jo', 'ya' ],
      },
      {
        combination: 'ju',
        word:        'juguete',
        syllable:    { w: 'ju', p: 'ju' },
        syllables:   [ 'ju', 'guete' ],
      },
    ],
  },
  {
    letter: 'k',
    combinations: [
      {
        combination: 'ka',
        word:        'karate',
        syllable:    { w: 'ka', p: 'ka' },
        syllables:   [ 'ka', 'rate' ],
      },
      {
        combination: 'ke',
        word:        'kermés',
        syllable:    { w: 'ke', p: 'ke' },
        syllables:   [ 'ke', 'rmés' ],
      },
      {
        combination: 'ki',
        word:        'kilo',
        syllable:    { w: 'ki', p: 'ki' },
        syllables:   [ 'ki', 'lo' ],
      },
      {
        combination: 'ko',
        word:        'koala',
        syllable:    { w: 'ko', p: 'ko' },
        syllables:   [ 'ko', 'ala' ],
      },
      {
        combination: 'ku',
        word:        'kung-fu',
        syllable:    { w: 'ku', p: 'ku' },
        syllables:   [ 'ku', 'ng-fu' ],
      },
    ],
  },
  {
    letter: 'l',
    combinations: [
      {
        combination: 'la',
        word:        'lana',
        syllable:    { w: 'la', p: 'la' },
        syllables:   [ 'la', 'na' ],
      },
      {
        combination: 'le',
        word:        'león',
        syllable:    { w: 'le', p: 'le' },
        syllables:   [ 'le', 'ón' ],
      },
      {
        combination: 'li',
        word:        'libro',
        syllable:    { w: 'li', p: 'li' },
        syllables:   [ 'li', 'bro'  ],
      },
      {
        combination: 'lo',
        word:        'lobo',
        syllable:    { w: 'lo', p: 'lo' },
        syllables:   [ 'lo', 'bo' ],
      },
      {
        combination: 'lu',
        word:        'luna',
        syllable:    { w: 'lu', p: 'lu' },
        syllables:   [ 'lu', 'na' ],
      },
    ],
  },
  {
    letter: 'm',
    combinations: [
      {
        combination: 'ma',
        word:        'mapa',
        syllable:    { w: 'ma', p: 'ma' },
        syllables:   [ 'ma', 'pa' ],
      },
      {
        combination: 'me',
        word:        'mesa',
        syllable:    { w: 'me', p: 'me' },
        syllables:   [ 'me', 'sa' ],
      },
      {
        combination: 'mi',
        word:        'mimo',
        syllable:    { w: 'mi', p: 'mi' },
        syllables:   [ 'mi', 'mo' ],
      },
      {
        combination: 'mo',
        word:        'mono',
        syllable:    { w: 'mo', p: 'mo' },
        syllables:   [ 'mo', 'no' ],
      },
      {
        combination: 'mu',
        word:        'mundo',
        syllable:    { w: 'mu', p: 'mu' },
        syllables:   [ 'mu', 'ndo'  ],
      },
    ],
  },
  {
    letter: 'n',
    combinations: [
      {
        combination: 'na',
        word:        'nave',
        syllable:    { w: 'na', p: 'na' },
        syllables:   [ 'na', 've' ],
      },
      {
        combination: 'ne',
        word:        'negro',
        syllable:    { w: 'ne', p: 'ne' },
        syllables:   [ 'ne', 'gro' ],
      },
      {
        combination: 'ni',
        word:        'niño',
        syllable:    { w: 'ni', p: 'ni' },
        syllables:   [ 'ni', 'ño' ],
      },
      {
        combination: 'no',
        word:        'nota',
        syllable:    { w: 'no', p: 'no' },
        syllables:   [ 'no', 'ta' ],
      },
      {
        combination: 'nu',
        word:        'nuez',
        syllable:    { w: 'nu', p: '.. nu' },
        syllables:   [ 'nu', 'ez' ],
      },
    ],
  },
  {
    letter: 'ñ',
    combinations: [
      {
        combination: 'ñ',
        word:        'ñandú',
        syllable:    { w: 'ña', p: 'ña' },
        syllables:   [ 'ña', 'ndú' ],
      },
      {
        combination: 'ñe',
        word:        'muñeco',
        syllable:    { w: 'ñe', p: 'ñe' },
        syllables:   [ 'mu', 'ñe', 'co' ],
      },
      {
        combination: 'ñi',
        word:        'albañil',
        syllable:    { w: 'ñi', p: 'ñi' },
        syllables:   [ 'alba', 'ñi', 'l' ],
      },
      {
        combination: 'ño',
        word:        'ñoño',
        syllable:    { w: 'ño', p: 'ño' },
        syllables:   [ 'ño', 'ño' ],
      },
      {
        combination: 'ñu',
        word:        'pañuelo',
        syllable:    { w: 'ñu', p: 'ñu' },
        syllables:   [ 'pa', 'ñu', 'elo' ],
      },
    ],
  },
  {
    letter: 'o',
    combinations: [
      {
        combination: 'oa',
        word:        'koala',
        syllable:    { w: 'oa', p: 'oa' },
        syllables:   [ 'k', 'oa', 'la' ],
      },
      {
        combination: 'oe',
        word:        'héroe',
        syllable:    { w: 'oe', p: 'oe' },
        syllables:   [ 'hér', 'oe' ],
      },
      {
        combination: 'oi',
        word:        'arcoiris',
        syllable:    { w: 'oi', p: 'oi' },
        syllables:   [ 'arc', 'oi', 'ris' ],
      },
      {
        combination: 'oo',
        word:        'zoología',
        syllable:    { w: 'oo', p: 'oo' },
        syllables:   [ 'z', 'oo', 'logía' ],
      },
    ],
  },
  {
    letter: 'p',
    combinations: [
      {
        combination: 'pa',
        word:        'pantalla',
        syllable:    { w: 'pa', p: 'pa' },
        syllables:   [ 'pa', 'ntalla' ],
      },
      {
        combination: 'pe',
        word:        'pera',
        syllable:    { w: 'pe', p: 'pe' },
        syllables:   [ 'pe', 'ra' ],
      },
      {
        combination: 'pi',
        word:        'pino',
        syllable:    { w: 'pi', p: 'pi' },
        syllables:   [ 'pi', 'no' ],
      },
      {
        combination: 'po',
        word:        'pollo',
        syllable:    { w: 'po', p: 'po' },
        syllables:   [ 'po', 'llo' ],
      },
      {
        combination: 'pu',
        word:        'puerta',
        syllable:    { w: 'pu', p: 'pu' },
        syllables:   [ 'pu', 'erta' ],
      },
    ],
  },
  {
    letter: 'q',
    combinations: [
      {
        combination: 'que',
        word:        'queso',
        syllable:    { w: 'que', p: 'que' },
        syllables:   [ 'que', 'so' ],
      },
      {
        combination: 'qui',
        word:        'quintal',
        syllable:    { w: 'qui', p: 'qui' },
        syllables:   [ 'qui', 'ntal' ],
      },
    ],
  },
  {
    letter: 'r',
    combinations: [
      {
        combination: 'ra',
        word:        'rana',
        syllable:    { w: 'ra', p: 'ra' },
        syllables:   [ 'ra', 'na' ],
      },
      {
        combination: 're',
        word:        'rey',
        syllable:    { w: 're', p: 're' },
        syllables:   [ 're', 'y' ],
      },
      {
        combination: 'ri',
        word:        'risa',
        syllable:    { w: 'ri', p: 'ri' },
        syllables:   [ 'ri', 'sa' ],
      },
      {
        combination: 'ro',
        word:        'rosa',
        syllable:    { w: 'ro', p: 'ro' },
        syllables:   [ 'ro', 'sa' ],
      },
      {
        combination: 'ru',
        word:        'rueda',
        syllable:    { w: 'ru', p: 'ru' },
        syllables:   [ 'ru', 'eda' ],
      },
    ],
  },
  {
    letter: 's',
    combinations: [
      {
        combination: 'sa',
        word:        'sapo',
        syllable:    { w: 'sa', p: 'sa' },
        syllables:   [ 'sa', 'po' ],
      },
      {
        combination: 'se',
        word:        'semáforo',
        syllable:    { w: 'se', p: 'se' },
        syllables:   [ 'se', 'máforo' ],
      },
      {
        combination: 'si',
        word:        'silla',
        syllable:    { w: 'si', p: 'si' },
        syllables:   [ 'si', 'lla' ],
      },
      {
        combination: 'so',
        word:        'sopa',
        syllable:    { w: 'so', p: 'so' },
        syllables:   [ 'so', 'pa' ],
      },
      {
        combination: 'su',
        word:        'sumar',
        syllable:    { w: 'su', p: 'su' },
        syllables:   [ 'su', 'mar' ],
      },
    ],
  },
  {
    letter: 't',
    combinations: [
      {
        combination: 'ta',
        word:        'taza',
        syllable:    { w: 'ta', p: 'ta' },
        syllables:   [ 'ta', 'za' ],
      },
      {
        combination: 'te',
        word:        'tenedor',
        syllable:    { w: 'te', p: 'te' },
        syllables:   [ 'te', 'nedor' ],
      },
      {
        combination: 'ti',
        word:        'tigre',
        syllable:    { w: 'ti', p: '.. ti' },
        syllables:   [ 'ti', 'gre' ],
      },
      {
        combination: 'to',
        word:        'tomate',
        syllable:    { w: 'to', p: '.. tow' },
        syllables:   [ 'to', 'mate' ],
      },
      {
        combination: 'tu',
        word:        'tucán',
        syllable:    { w: 'tu', p: 'tu' },
        syllables:   [ 'tu', 'cán' ],
      },
    ],
  },
  {
    letter: 'u',
    combinations: [
      {
        combination: 'ua',
        word:        'agua',
        syllable:    { w: 'ua', p: '.. uha' },
        syllables:   [ 'ag', 'ua' ],
      },
      {
        combination: 'ue',
        word:        'huevo',
        syllable:    { w: 'ue', p: '.. uhe' },
        syllables:   [ 'h', 'ue', 'vo' ],
      },
      {
        combination: 'ui',
        word:        'cuidado',
        syllable:    { w: 'ui', p: '.. uy' },
        syllables:   [ 'c', 'ui', 'dado' ],
      },
      {
        combination: 'uo',
        word:        'monstruo',
        syllable:    { w: 'uo', p: 'uo' },
        syllables:   [ 'monstr', 'uo' ],
      },
    ],
  },
  {
    letter: 'v',
    combinations: [
      {
        combination: 'va',
        word:        'vaca',
        syllable:    { w: 'va', p: 'va' },
        syllables:   [ 'va', 'ca' ],
      },
      {
        combination: 've',
        word:        'vela',
        syllable:    { w: 've', p: 've' },
        syllables:   [ 've', 'la' ],
      },
      {
        combination: 'vi',
        word:        'viento',
        syllable:    { w: 'vi', p: 'vi' },
        syllables:   [ 'vi', 'ento' ],
      },
      {
        combination: 'vo',
        word:        'volcán',
        syllable:    { w: 'vo', p: 'vo' },
        syllables:   [ 'vo', 'lcán' ],
      },
      {
        combination: 'vu',
        word:        'vuelo',
        syllable:    { w: 'vu', p: 'vu' },
        syllables:   [ 'vu', 'elo' ],
      },
    ],
  },
  {
    letter: 'w',
    combinations: [
      {
        combination: 'wa',
        word:        'waterpolo',
        syllable:    { w: 'wa', p: 'wa' },
        syllables:   [ 'wa', 'terpolo' ],
      },
      {
        combination: 'we',
        word:        'web',
        syllable:    { w: 'we', p: 'we' },
        syllables:   [ 'we', 'b' ],
      },
      {
        combination: 'wi',
        word:        'sándwich',
        syllable:    { w: 'wi', p: 'wi' },
        syllables:   [ 'sánd', 'wi', 'ch' ],
      },
      {
        combination: 'wo',
        word:        'wow',
        syllable:    { w: 'wo', p: 'wo' },
        syllables:   [ 'wo', 'w' ],
      },
      {
        combination: 'wu',
        word:        'wu',
        syllable:    { w: 'wu', p: 'wu' },
        syllables:   [ 'wu' ],
      },
    ],
  },
  {
    letter: 'x',
    combinations: [
      {
        combination: 'xa',
        word:        'exacto',
        syllable:    { w: 'xa', p: 'xa' },
        syllables:   [ 'e', 'xa', 'cto' ],
      },
      {
        combination: 'xe',
        word:        'boxeador',
        syllable:    { w: 'xe', p: 'xe' },
        syllables:   [ 'bo', 'xe', 'ador' ],
      },
      {
        combination: 'xi',
        word:        'taxi',
        syllable:    { w: 'xi', p: 'xi' },
        syllables:   [ 'ta', 'xi' ],
      },
      {
        combination: 'xo',
        word:        'saxofón',
        syllable:    { w: 'xo', p: 'so' },
        syllables:   [ 'sa', 'xo', 'fón' ],
      },
      {
        combination: 'xu',
        word:        'sexualidad',
        syllable:    { w: 'xu', p: 'xu' },
        syllables:   [ 'se', 'xu', 'alidad' ],
      },
    ],
  },
  {
    letter: 'y',
    combinations: [
      {
        combination: 'ya',
        word:        'yate',
        syllable:    { w: 'ya', p: 'ya' },
        syllables:   [ 'ya', 'te' ],
      },
      {
        combination: 'ye',
        word:        'yeso',
        syllable:    { w: 'ye', p: '.. ihe' },
        syllables:   [ 'ye', 'so' ],
      },
      {
        combination: 'yi',
        word:        'rayito',
        syllable:    { w: 'yi', p: 'yi' },
        syllables:   [ 'ra', 'yi', 'to' ],
      },
      {
        combination: 'yo',
        word:        'yoyo',
        syllable:    { w: 'yo', p: 'yo' },
        syllables:   [ 'yo', 'yo' ],
      },
      {
        combination: 'yu',
        word:        'yunque',
        syllable:    { w: 'yu', p: 'yu' },
        syllables:   [ 'yu', 'nque' ],
      },
    ],
  },
  {
    letter: 'z',
    combinations: [
      {
        combination: 'za',
        word:        'zapato',
        syllable:    { w: 'za', p: 'za' },
        syllables:   [ 'za', 'pato' ],
      },
      {
        combination: 'ze',
        word:        'zeta',
        syllable:    { w: 'ze', p: 'ze' },
        syllables:   [ 'ze', 'ta' ],
      },
      {
        combination: 'zi',
        word:        'zigzag',
        syllable:    { w: 'zi', p: 'zi' },
        syllables:   [ 'zi', 'gzag' ],
      },
      {
        combination: 'zo',
        word:        'zorro',
        syllable:    { w: 'zo', p: 'zo' },
        syllables:   [ 'zo', 'rro' ],
      },
      {
        combination: 'zu',
        word:        'azul',
        syllable:    { w: 'zu', p: 'zu' },
        syllables:   [ 'a', 'zu', 'l' ],
      },
    ],
  },
];

export const coordinatesList: CreateCoordinateDto[] = [

  {
    letter: 'a',
    coordinates: [
      [
        { x: 99, y: 56 },
        { x: 99, y: 56 },
        { x: 101, y: 54 },
        { x: 119, y: 45 },
        { x: 152, y: 45 },
        { x: 166, y: 51 },
        { x: 180, y: 66 },
        { x: 190, y: 91 },
        { x: 199, y: 147 },
        { x: 201, y: 191 },
        { x: 203, y: 230 },
        { x: 207, y: 245 },
        { x: 208, y: 250 },
        { x: 208, y: 252 },
        { x: 204, y: 235 },
        { x: 191, y: 207 },
        { x: 163, y: 176 },
        { x: 130, y: 153 },
        { x: 91, y: 147 },
        { x: 67, y: 164 },
        { x: 61, y: 205 },
        { x: 71, y: 237 },
        { x: 93, y: 261 },
        { x: 150, y: 277 },
        { x: 194, y: 269 },
        { x: 213, y: 263 },
        { x: 218, y: 261 },
      ],
    ],
  },
  {
    letter: 'A',
    coordinates: [
      [
        { x: 91, y: 240 },
        { x: 91, y: 240 },
        { x: 93, y: 218 },
        { x: 104, y: 177 },
        { x: 126, y: 111 },
        { x: 136, y: 77 },
        { x: 143, y: 53 },
        { x: 147, y: 42 },
        { x: 154, y: 47 },
        { x: 169, y: 83 },
        { x: 193, y: 148 },
        { x: 209, y: 197 },
        { x: 229, y: 234 },
      ],
      [
        { x: 104, y: 191 },
        { x: 104, y: 191 },
        { x: 161, y: 189 },
        { x: 212, y: 190 },
      ],
    ],
  },
  {
    letter: 'b',
    coordinates: [
      [
        { x: 109, y: 31 },
        { x: 109, y: 31 },
        { x: 108, y: 51 },
        { x: 109, y: 91 },
        { x: 111, y: 140 },
        { x: 113, y: 178 },
        { x: 113, y: 205 },
        { x: 113, y: 227 },
        { x: 113, y: 238 },
        { x: 113, y: 245 },
        { x: 113, y: 247 },
        { x: 113, y: 242 },
        { x: 113, y: 216 },
        { x: 119, y: 182 },
        { x: 125, y: 157 },
        { x: 133, y: 141 },
        { x: 147, y: 127 },
        { x: 167, y: 123 },
        { x: 185, y: 131 },
        { x: 196, y: 148 },
        { x: 202, y: 179 },
        { x: 196, y: 206 },
        { x: 181, y: 224 },
        { x: 163, y: 236 },
        { x: 135, y: 243 },
        { x: 117, y: 243 },
      ],
    ],
  },
  {
    letter: 'B',
    coordinates: [
      [
        { x: 95, y: 51 },
        { x: 95, y: 51 },
        { x: 96, y: 67 },
        { x: 99, y: 113 },
        { x: 97, y: 165 },
        { x: 95, y: 202 },
        { x: 95, y: 231 },
        { x: 95, y: 241 },
        { x: 95, y: 246 },
      ],
      [
        { x: 83, y: 47 },
        { x: 83, y: 47 },
        { x: 88, y: 43 },
        { x: 97, y: 38 },
        { x: 125, y: 35 },
        { x: 143, y: 41 },
        { x: 155, y: 52 },
        { x: 163, y: 72 },
        { x: 159, y: 97 },
        { x: 142, y: 116 },
        { x: 123, y: 132 },
        { x: 114, y: 139 },
        { x: 108, y: 144 },
        { x: 109, y: 145 },
        { x: 124, y: 143 },
        { x: 144, y: 143 },
        { x: 165, y: 145 },
        { x: 187, y: 158 },
        { x: 198, y: 173 },
        { x: 200, y: 206 },
        { x: 189, y: 226 },
        { x: 168, y: 245 },
        { x: 141, y: 256 },
        { x: 107, y: 258 },
        { x: 91, y: 254 },
      ],
    ],
  },
  {
    letter: 'c',
    coordinates: [
      [
        { x: 182, y: 137 },
        { x: 182, y: 137 },
        { x: 177, y: 132 },
        { x: 168, y: 124 },
        { x: 141, y: 127 },
        { x: 130, y: 140 },
        { x: 121, y: 165 },
        { x: 120, y: 203 },
        { x: 129, y: 219 },
        { x: 147, y: 233 },
        { x: 173, y: 228 },
        { x: 185, y: 217 },
        { x: 189, y: 210 },
      ],
    ],
  },
  {
    letter: 'C',
    coordinates: [
      [
        { x: 183, y: 98 },
        { x: 183, y: 98 },
        { x: 173, y: 87 },
        { x: 149, y: 77 },
        { x: 126, y: 81 },
        { x: 108, y: 99 },
        { x: 93, y: 130 },
        { x: 87, y: 188 },
        { x: 97, y: 215 },
        { x: 115, y: 232 },
        { x: 154, y: 234 },
        { x: 169, y: 223 },
        { x: 180, y: 212 },
        { x: 187, y: 200 },
      ],
    ],
  },
  {
    letter: 'd',
    coordinates: [
      [
        { x: 201, y: 28 },
        { x: 201, y: 28 },
        { x: 201, y: 41 },
        { x: 202, y: 85 },
        { x: 203, y: 129 },
        { x: 204, y: 170 },
        { x: 203, y: 202 },
        { x: 203, y: 219 },
        { x: 202, y: 225 },
        { x: 201, y: 229 },
        { x: 199, y: 215 },
        { x: 190, y: 180 },
        { x: 179, y: 157 },
        { x: 165, y: 137 },
        { x: 144, y: 127 },
        { x: 119, y: 131 },
        { x: 105, y: 143 },
        { x: 93, y: 177 },
        { x: 93, y: 206 },
        { x: 101, y: 219 },
        { x: 116, y: 232 },
        { x: 135, y: 239 },
        { x: 173, y: 240 },
        { x: 190, y: 235 },
        { x: 199, y: 230 },
        { x: 203, y: 229 },
      ],
    ],
  },
  {
    letter: 'D',
    coordinates: [
      [
        { x: 94, y: 75 },
        { x: 94, y: 75 },
        { x: 95, y: 81 },
        { x: 95, y: 112 },
        { x: 95, y: 151 },
        { x: 95, y: 189 },
        { x: 95, y: 209 },
        { x: 95, y: 216 },
        { x: 95, y: 221 },
      ],
      [
        { x: 94, y: 73 },
        { x: 94, y: 73 },
        { x: 100, y: 73 },
        { x: 123, y: 74 },
        { x: 156, y: 79 },
        { x: 169, y: 88 },
        { x: 189, y: 105 },
        { x: 200, y: 127 },
        { x: 207, y: 155 },
        { x: 205, y: 179 },
        { x: 196, y: 199 },
        { x: 177, y: 215 },
        { x: 170, y: 220 },
        { x: 159, y: 225 },
        { x: 139, y: 229 },
        { x: 125, y: 231 },
        { x: 103, y: 231 },
        { x: 96, y: 229 },
        { x: 90, y: 227 },
        { x: 86, y: 227 },
      ],
    ],
  },
  {
    letter: 'e',
    coordinates: [
      [
        { x: 100, y: 165 },
        { x: 100, y: 165 },
        { x: 101, y: 162 },
        { x: 117, y: 163 },
        { x: 159, y: 161 },
        { x: 182, y: 158 },
        { x: 191, y: 157 },
        { x: 194, y: 155 },
        { x: 195, y: 148 },
        { x: 193, y: 123 },
        { x: 185, y: 107 },
        { x: 171, y: 94 },
        { x: 147, y: 91 },
        { x: 131, y: 98 },
        { x: 111, y: 115 },
        { x: 99, y: 143 },
        { x: 94, y: 185 },
        { x: 97, y: 214 },
        { x: 108, y: 229 },
        { x: 127, y: 243 },
        { x: 158, y: 247 },
        { x: 176, y: 239 },
        { x: 191, y: 224 },
        { x: 199, y: 211 },
        { x: 201, y: 205 },
      ],
    ],
  },
  {
    letter: 'E',
    coordinates: [
      [
        { x: 179, y: 61 },
        { x: 179, y: 61 },
        { x: 165, y: 60 },
        { x: 117, y: 63 },
        { x: 103, y: 63 },
        { x: 101, y: 65 },
        { x: 99, y: 90 },
        { x: 103, y: 140 },
        { x: 105, y: 207 },
        { x: 108, y: 238 },
        { x: 110, y: 245 },
        { x: 111, y: 248 },
        { x: 141, y: 247 },
        { x: 178, y: 244 },
        { x: 196, y: 244 },
        { x: 200, y: 245 },
      ],
      [
        { x: 105, y: 165 },
        { x: 105, y: 165 },
        { x: 108, y: 163 },
        { x: 143, y: 159 },
        { x: 163, y: 156 },
      ],
    ],
  },
  {
    letter: 'f',
    coordinates: [
      [
        { x: 203, y: 68 },
        { x: 203, y: 68 },
        { x: 202, y: 63 },
        { x: 196, y: 53 },
        { x: 185, y: 43 },
        { x: 174, y: 38 },
        { x: 161, y: 39 },
        { x: 150, y: 47 },
        { x: 141, y: 67 },
        { x: 137, y: 109 },
        { x: 138, y: 140 },
        { x: 141, y: 171 },
        { x: 141, y: 209 },
        { x: 141, y: 227 },
      ],
      [
        { x: 116, y: 151 },
        { x: 116, y: 151 },
        { x: 117, y: 152 },
        { x: 139, y: 153 },
        { x: 165, y: 152 },
        { x: 180, y: 150 },
      ],
    ],
  },
  {
    letter: 'F',
    coordinates: [
      [
        { x: 201, y: 53 },
        { x: 201, y: 53 },
        { x: 185, y: 54 },
        { x: 162, y: 58 },
        { x: 136, y: 61 },
        { x: 129, y: 62 },
        { x: 127, y: 66 },
        { x: 127, y: 90 },
        { x: 130, y: 134 },
        { x: 133, y: 183 },
        { x: 133, y: 220 },
        { x: 133, y: 234 },
      ],
      [
        { x: 131, y: 149 },
        { x: 131, y: 149 },
        { x: 133, y: 151 },
        { x: 162, y: 147 },
        { x: 185, y: 143 },
      ],
    ],
  },
  {
    letter: 'g',
    coordinates: [
      [
        { x: 175, y: 81 },
        { x: 175, y: 81 },
        { x: 172, y: 78 },
        { x: 153, y: 72 },
        { x: 131, y: 71 },
        { x: 117, y: 77 },
        { x: 102, y: 91 },
        { x: 95, y: 123 },
        { x: 98, y: 140 },
        { x: 107, y: 152 },
        { x: 121, y: 163 },
        { x: 141, y: 169 },
        { x: 159, y: 165 },
        { x: 171, y: 155 },
        { x: 181, y: 139 },
        { x: 187, y: 118 },
        { x: 185, y: 95 },
        { x: 178, y: 85 },
        { x: 171, y: 79 },
      ],
      [
        { x: 194, y: 67 },
        { x: 194, y: 67 },
        { x: 193, y: 71 },
        { x: 192, y: 83 },
        { x: 192, y: 102 },
        { x: 192, y: 122 },
        { x: 193, y: 143 },
        { x: 195, y: 165 },
        { x: 197, y: 189 },
        { x: 197, y: 212 },
        { x: 196, y: 231 },
        { x: 189, y: 242 },
        { x: 175, y: 252 },
        { x: 153, y: 258 },
        { x: 129, y: 261 },
        { x: 115, y: 261 },
        { x: 111, y: 262 },
      ],
    ],
  },
  {
    letter: 'G',
    coordinates: [
      [
        { x: 201, y: 94 },
        { x: 201, y: 94 },
        { x: 197, y: 93 },
        { x: 185, y: 86 },
        { x: 159, y: 81 },
        { x: 137, y: 83 },
        { x: 121, y: 89 },
        { x: 105, y: 101 },
        { x: 90, y: 121 },
        { x: 80, y: 154 },
        { x: 79, y: 181 },
        { x: 84, y: 200 },
        { x: 93, y: 219 },
        { x: 111, y: 237 },
        { x: 131, y: 248 },
        { x: 159, y: 252 },
        { x: 175, y: 249 },
        { x: 191, y: 240 },
        { x: 203, y: 225 },
        { x: 211, y: 207 },
        { x: 219, y: 181 },
        { x: 220, y: 171 },
        { x: 219, y: 169 },
        { x: 207, y: 171 },
        { x: 164, y: 175 },
        { x: 152, y: 176 },
      ],
    ],
  },
  {
    letter: 'h',
    coordinates: [
      [
        { x: 111, y: 38 },
        { x: 111, y: 38 },
        { x: 112, y: 55 },
        { x: 113, y: 99 },
        { x: 113, y: 141 },
        { x: 115, y: 179 },
        { x: 114, y: 211 },
        { x: 114, y: 219 },
        { x: 114, y: 223 },
        { x: 117, y: 208 },
        { x: 129, y: 165 },
        { x: 140, y: 143 },
        { x: 153, y: 129 },
        { x: 175, y: 125 },
        { x: 185, y: 138 },
        { x: 192, y: 165 },
        { x: 193, y: 191 },
        { x: 191, y: 214 },
        { x: 192, y: 226 },
      ],
    ],
  },
  {
    letter: 'H',
    coordinates: [
      [
        { x: 113, y: 60 },
        { x: 113, y: 60 },
        { x: 113, y: 95 },
        { x: 117, y: 147 },
        { x: 121, y: 197 },
        { x: 121, y: 218 },
        { x: 122, y: 227 },
      ],
      [
        { x: 179, y: 63 },
        { x: 179, y: 63 },
        { x: 177, y: 72 },
        { x: 177, y: 109 },
        { x: 178, y: 153 },
        { x: 181, y: 190 },
        { x: 182, y: 215 },
        { x: 184, y: 229 },
      ],
      [
        { x: 109, y: 158 },
        { x: 109, y: 158 },
        { x: 114, y: 156 },
        { x: 142, y: 156 },
        { x: 173, y: 154 },
        { x: 182, y: 153 },
      ],
    ],
  },
  {
    letter: 'i',
    coordinates: [
      [
        { x: 149, y: 132 },
        { x: 149, y: 132 },
        { x: 149, y: 139 },
        { x: 149, y: 166 },
        { x: 150, y: 189 },
        { x: 151, y: 213 },
        { x: 151, y: 222 },
        { x: 153, y: 229 },
      ],
      [
        { x: 151, y: 89 },
        { x: 151, y: 89 },
        { x: 149, y: 91 },
      ],
    ],
  },
  {
    letter: 'I',
    coordinates: [
      [
        { x: 89, y: 79 },
        { x: 89, y: 79 },
        { x: 99, y: 79 },
        { x: 147, y: 77 },
        { x: 180, y: 75 },
        { x: 205, y: 73 },
      ],
      [
        { x: 84, y: 244 },
        { x: 84, y: 244 },
        { x: 88, y: 242 },
        { x: 105, y: 241 },
        { x: 138, y: 241 },
        { x: 167, y: 240 },
        { x: 189, y: 241 },
        { x: 211, y: 240 },
        { x: 220, y: 241 },
      ],
      [
        { x: 144, y: 80 },
        { x: 144, y: 80 },
        { x: 147, y: 95 },
        { x: 149, y: 122 },
        { x: 151, y: 149 },
        { x: 151, y: 187 },
        { x: 150, y: 211 },
        { x: 149, y: 223 },
        { x: 150, y: 240 },
      ],
    ],
  },
  {
    letter: 'j',
    coordinates: [
      [
        { x: 157, y: 83 },
        { x: 157, y: 83 },
        { x: 156, y: 103 },
        { x: 158, y: 137 },
        { x: 161, y: 178 },
        { x: 164, y: 213 },
        { x: 165, y: 245 },
        { x: 157, y: 262 },
        { x: 140, y: 275 },
        { x: 101, y: 265 },
        { x: 83, y: 242 },
      ],
      [
        { x: 161, y: 34 },
        { x: 161, y: 34 },
        { x: 159, y: 37 },
        { x: 159, y: 41 },
        { x: 167, y: 41 },
      ],
    ],
  },
  {
    letter: 'J',
    coordinates: [
      [
        { x: 161, y: 53 },
        { x: 161, y: 53 },
        { x: 157, y: 65 },
        { x: 158, y: 95 },
        { x: 161, y: 140 },
        { x: 161, y: 177 },
        { x: 162, y: 211 },
        { x: 155, y: 236 },
        { x: 143, y: 249 },
        { x: 112, y: 255 },
        { x: 81, y: 228 },
        { x: 70, y: 203 },
      ],
      [
        { x: 83, y: 62 },
        { x: 83, y: 62 },
        { x: 95, y: 59 },
        { x: 132, y: 56 },
        { x: 177, y: 59 },
        { x: 215, y: 59 },
        { x: 228, y: 59 },
      ],
    ],
  },
  {
    letter: 'k',
    coordinates: [
      [
        { x: 119, y: 83 },
        { x: 119, y: 83 },
        { x: 119, y: 119 },
        { x: 115, y: 181 },
        { x: 118, y: 221 },
      ],
      [
        { x: 175, y: 90 },
        { x: 175, y: 90 },
        { x: 164, y: 111 },
        { x: 145, y: 147 },
        { x: 129, y: 171 },
        { x: 123, y: 179 },
        { x: 123, y: 183 },
        { x: 137, y: 190 },
        { x: 161, y: 205 },
        { x: 181, y: 215 },
      ],
    ],
  },
  {
    letter: 'K',
    coordinates: [
      [
        { x: 123, y: 52 },
        { x: 123, y: 52 },
        { x: 121, y: 72 },
        { x: 121, y: 118 },
        { x: 120, y: 169 },
        { x: 119, y: 211 },
        { x: 118, y: 236 },
      ],
      [
        { x: 205, y: 44 },
        { x: 205, y: 44 },
        { x: 199, y: 55 },
        { x: 187, y: 80 },
        { x: 160, y: 130 },
        { x: 138, y: 169 },
        { x: 126, y: 182 },
        { x: 121, y: 188 },
        { x: 121, y: 190 },
        { x: 130, y: 197 },
        { x: 147, y: 209 },
        { x: 171, y: 221 },
        { x: 196, y: 235 },
        { x: 211, y: 243 },
      ],
    ],
  },
  {
    letter: 'l',
    coordinates: [
      [
        { x: 149, y: 57 },
        { x: 149, y: 57 },
        { x: 149, y: 68 },
        { x: 149, y: 110 },
        { x: 149, y: 174 },
        { x: 147, y: 209 },
        { x: 147, y: 221 },
      ],
    ],
  },
  {
    letter: 'L',
    coordinates: [
      [
        { x: 105, y: 46 },
        { x: 105, y: 46 },
        { x: 106, y: 66 },
        { x: 108, y: 135 },
        { x: 108, y: 187 },
        { x: 106, y: 214 },
        { x: 106, y: 221 },
        { x: 105, y: 225 },
        { x: 111, y: 225 },
        { x: 139, y: 224 },
        { x: 179, y: 223 },
        { x: 205, y: 223 },
        { x: 213, y: 223 },
      ],
    ],
  },
  {
    letter: 'm',
    coordinates: [
      [
        { x: 58, y: 107 },
        { x: 58, y: 107 },
        { x: 59, y: 111 },
        { x: 59, y: 123 },
        { x: 59, y: 144 },
        { x: 59, y: 159 },
        { x: 59, y: 179 },
        { x: 60, y: 186 },
        { x: 59, y: 207 },
        { x: 59, y: 216 },
        { x: 57, y: 221 },
        { x: 59, y: 218 },
        { x: 61, y: 199 },
        { x: 64, y: 189 },
        { x: 67, y: 175 },
        { x: 71, y: 161 },
        { x: 75, y: 147 },
        { x: 82, y: 133 },
        { x: 94, y: 123 },
        { x: 105, y: 118 },
        { x: 118, y: 116 },
        { x: 133, y: 118 },
        { x: 143, y: 131 },
        { x: 147, y: 142 },
        { x: 151, y: 161 },
        { x: 152, y: 180 },
        { x: 151, y: 203 },
        { x: 151, y: 215 },
        { x: 151, y: 220 },
        { x: 151, y: 216 },
        { x: 153, y: 195 },
        { x: 155, y: 177 },
        { x: 159, y: 159 },
        { x: 166, y: 146 },
        { x: 175, y: 131 },
        { x: 183, y: 122 },
        { x: 195, y: 117 },
        { x: 211, y: 114 },
        { x: 218, y: 113 },
        { x: 224, y: 115 },
        { x: 231, y: 120 },
        { x: 237, y: 135 },
        { x: 241, y: 149 },
        { x: 242, y: 178 },
        { x: 241, y: 199 },
        { x: 239, y: 216 },
        { x: 238, y: 222 },
        { x: 241, y: 228 },
      ],
    ],
  },
  {
    letter: 'M',
    coordinates: [
      [
        { x: 87, y: 235 },
        { x: 87, y: 235 },
        { x: 86, y: 230 },
        { x: 84, y: 211 },
        { x: 84, y: 161 },
        { x: 87, y: 119 },
        { x: 87, y: 89 },
        { x: 87, y: 84 },
        { x: 89, y: 83 },
        { x: 101, y: 92 },
        { x: 115, y: 109 },
        { x: 134, y: 134 },
        { x: 143, y: 146 },
        { x: 148, y: 152 },
        { x: 149, y: 155 },
        { x: 151, y: 154 },
        { x: 157, y: 150 },
        { x: 173, y: 131 },
        { x: 190, y: 111 },
        { x: 205, y: 94 },
        { x: 213, y: 86 },
        { x: 217, y: 83 },
        { x: 220, y: 91 },
        { x: 223, y: 120 },
        { x: 225, y: 158 },
        { x: 227, y: 191 },
        { x: 227, y: 218 },
        { x: 226, y: 245 },
        { x: 226, y: 252 },
      ],
    ],
  },
  {
    letter: 'n',
    coordinates: [
      [
        { x: 94, y: 115 },
        { x: 94, y: 115 },
        { x: 94, y: 123 },
        { x: 102, y: 170 },
        { x: 105, y: 206 },
        { x: 107, y: 216 },
        { x: 107, y: 211 },
        { x: 109, y: 178 },
        { x: 112, y: 147 },
        { x: 118, y: 124 },
        { x: 138, y: 103 },
        { x: 150, y: 97 },
        { x: 173, y: 105 },
        { x: 183, y: 119 },
        { x: 190, y: 138 },
        { x: 196, y: 177 },
        { x: 200, y: 208 },
        { x: 205, y: 219 },
      ],
    ],
  }, {
    letter: 'N',
    coordinates: [
      [
        { x: 100, y: 233 },
        { x: 100, y: 233 },
        { x: 99, y: 229 },
        { x: 99, y: 225 },
        { x: 99, y: 199 },
        { x: 97, y: 165 },
        { x: 97, y: 125 },
        { x: 95, y: 99 },
        { x: 95, y: 89 },
        { x: 98, y: 90 },
        { x: 109, y: 109 },
        { x: 127, y: 133 },
        { x: 145, y: 162 },
        { x: 165, y: 189 },
        { x: 179, y: 209 },
        { x: 192, y: 224 },
        { x: 201, y: 233 },
        { x: 204, y: 228 },
        { x: 205, y: 205 },
        { x: 204, y: 165 },
        { x: 204, y: 117 },
        { x: 203, y: 85 },
      ],
    ],
  },
  {
    letter: 'ñ',
    coordinates: [
      [
        { x: 103, y: 107 },
        { x: 103, y: 107 },
        { x: 103, y: 112 },
        { x: 107, y: 149 },
        { x: 107, y: 185 },
        { x: 107, y: 216 },
        { x: 108, y: 223 },
        { x: 109, y: 212 },
        { x: 112, y: 177 },
        { x: 117, y: 142 },
        { x: 131, y: 125 },
        { x: 151, y: 113 },
        { x: 179, y: 113 },
        { x: 186, y: 119 },
        { x: 193, y: 143 },
        { x: 194, y: 167 },
        { x: 193, y: 186 },
        { x: 193, y: 211 },
        { x: 198, y: 223 },
      ],
      [
        { x: 116, y: 82 },
        { x: 116, y: 82 },
        { x: 114, y: 79 },
        { x: 119, y: 71 },
        { x: 129, y: 67 },
        { x: 141, y: 69 },
        { x: 151, y: 73 },
        { x: 167, y: 76 },
        { x: 182, y: 73 },
        { x: 196, y: 57 },
      ],
    ],
  },
  {
    letter: 'Ñ',
    coordinates: [
      [
        { x: 105, y: 223 },
        { x: 105, y: 223 },
        { x: 105, y: 203 },
        { x: 106, y: 153 },
        { x: 105, y: 113 },
        { x: 104, y: 92 },
        { x: 107, y: 90 },
        { x: 118, y: 110 },
        { x: 136, y: 135 },
        { x: 161, y: 168 },
        { x: 178, y: 191 },
        { x: 193, y: 208 },
        { x: 203, y: 217 },
        { x: 207, y: 216 },
        { x: 207, y: 178 },
        { x: 205, y: 135 },
        { x: 203, y: 108 },
        { x: 202, y: 87 },
      ],
      [
        { x: 117, y: 50 },
        { x: 117, y: 50 },
        { x: 117, y: 47 },
        { x: 127, y: 45 },
        { x: 146, y: 43 },
        { x: 169, y: 46 },
        { x: 190, y: 47 },
        { x: 199, y: 46 },
      ],
    ],
  },
  {
    letter: 'o',
    coordinates: [
      [
        { x: 150, y: 117 },
        { x: 150, y: 117 },
        { x: 138, y: 118 },
        { x: 122, y: 131 },
        { x: 109, y: 153 },
        { x: 105, y: 197 },
        { x: 119, y: 215 },
        { x: 137, y: 223 },
        { x: 166, y: 222 },
        { x: 187, y: 197 },
        { x: 193, y: 165 },
        { x: 187, y: 143 },
        { x: 171, y: 128 },
        { x: 139, y: 118 },
      ],
    ],
  },
  {
    letter: 'O',
    coordinates: [
      [
        { x: 143, y: 76 },
        { x: 143, y: 76 },
        { x: 126, y: 77 },
        { x: 101, y: 90 },
        { x: 84, y: 124 },
        { x: 81, y: 183 },
        { x: 97, y: 205 },
        { x: 122, y: 221 },
        { x: 173, y: 219 },
        { x: 197, y: 193 },
        { x: 207, y: 155 },
        { x: 203, y: 114 },
        { x: 190, y: 95 },
        { x: 169, y: 81 },
        { x: 141, y: 76 },
      ],
    ],
  },
  {
    letter: 'p',
    coordinates: [
      [
        { x: 107, y: 115 },
        { x: 107, y: 115 },
        { x: 108, y: 138 },
        { x: 111, y: 182 },
        { x: 113, y: 229 },
        { x: 113, y: 255 },
        { x: 113, y: 270 },
      ],
      [
        { x: 104, y: 116 },
        { x: 104, y: 116 },
        { x: 108, y: 115 },
        { x: 124, y: 113 },
        { x: 145, y: 112 },
        { x: 164, y: 116 },
        { x: 177, y: 134 },
        { x: 182, y: 155 },
        { x: 181, y: 179 },
        { x: 173, y: 193 },
        { x: 160, y: 207 },
        { x: 143, y: 217 },
        { x: 125, y: 219 },
        { x: 119, y: 220 },
      ],
    ],

  },
  {
    letter: 'P',
    coordinates: [
      [
        { x: 96, y: 42 },
        { x: 96, y: 42 },
        { x: 99, y: 67 },
        { x: 107, y: 122 },
        { x: 111, y: 175 },
        { x: 113, y: 211 },
        { x: 113, y: 221 },
      ],
      [
        { x: 93, y: 42 },
        { x: 93, y: 42 },
        { x: 99, y: 39 },
        { x: 111, y: 33 },
        { x: 141, y: 29 },
        { x: 157, y: 37 },
        { x: 173, y: 49 },
        { x: 181, y: 67 },
        { x: 185, y: 102 },
        { x: 177, y: 116 },
        { x: 157, y: 135 },
        { x: 133, y: 145 },
        { x: 115, y: 151 },
      ],
    ],
  },
  {
    letter: 'q',
    coordinates: [
      [
        { x: 191, y: 89 },
        { x: 191, y: 89 },
        { x: 186, y: 85 },
        { x: 173, y: 80 },
        { x: 145, y: 77 },
        { x: 120, y: 82 },
        { x: 101, y: 106 },
        { x: 97, y: 141 },
        { x: 105, y: 159 },
        { x: 121, y: 172 },
        { x: 149, y: 174 },
        { x: 167, y: 159 },
        { x: 181, y: 138 },
        { x: 189, y: 115 },
        { x: 195, y: 96 },
        { x: 197, y: 89 },
        { x: 197, y: 119 },
        { x: 197, y: 175 },
        { x: 197, y: 219 },
        { x: 197, y: 251 },
        { x: 199, y: 257 },
      ],
    ],
  },
  {
    letter: 'Q',
    coordinates: [
      [
        { x: 163, y: 46 },
        { x: 163, y: 46 },
        { x: 153, y: 47 },
        { x: 134, y: 56 },
        { x: 117, y: 75 },
        { x: 99, y: 112 },
        { x: 94, y: 167 },
        { x: 102, y: 190 },
        { x: 115, y: 211 },
        { x: 137, y: 229 },
        { x: 178, y: 226 },
        { x: 196, y: 218 },
        { x: 213, y: 191 },
        { x: 221, y: 147 },
        { x: 221, y: 114 },
        { x: 212, y: 89 },
        { x: 199, y: 72 },
        { x: 182, y: 57 },
        { x: 157, y: 49 },
      ],
      [
        { x: 167, y: 188 },
        { x: 167, y: 188 },
        { x: 177, y: 199 },
        { x: 199, y: 215 },
        { x: 219, y: 232 },
        {
          x: 231, y: 240,
        },
      ],
    ],
  },
  {
    letter: 'r',
    coordinates: [
      [
        { x: 116, y: 101 },
        { x: 116, y: 101 },
        { x: 115, y: 105 },
        { x: 117, y: 129 },
        { x: 120, y: 163 },
        { x: 121, y: 189 },
        { x: 123, y: 212 },
        { x: 123, y: 218 },
        { x: 123, y: 220 },
        { x: 122, y: 203 },
        { x: 124, y: 166 },
        { x: 131, y: 139 },
        { x: 141, y: 119 },
        { x: 156, y: 99 },
        { x: 177, y: 93 },
        { x: 186, y: 96 },
      ],
    ],
  },
  {
    letter: 'R',
    coordinates: [
      [
        { x: 80, y: 45 },
        { x: 80, y: 45 },
        { x: 87, y: 70 },
        { x: 103, y: 120 },
        { x: 115, y: 203 },
        { x: 116, y: 237 },
        { x: 115, y: 230 },
        { x: 113, y: 142 },
        { x: 127, y: 75 },
        { x: 149, y: 45 },
        { x: 185, y: 49 },
        { x: 184, y: 123 },
        { x: 141, y: 196 },
        { x: 117, y: 214 },
        { x: 113, y: 203 },
        { x: 159, y: 227 },
        { x: 246, y: 227 },
      ],
    ],
  },
  {
    letter: 's',
    coordinates: [
      [
        { x: 167, y: 117 },
        { x: 167, y: 117 },
        { x: 159, y: 111 },
        { x: 143, y: 109 },
        { x: 135, y: 113 },
        { x: 128, y: 135 },
        { x: 128, y: 149 },
        { x: 139, y: 161 },
        { x: 156, y: 168 },
        { x: 169, y: 175 },
        { x: 179, y: 193 },
        { x: 175, y: 217 },
        { x: 161, y: 228 },
        { x: 122, y: 223 },
        { x: 112, y: 201 }],
    ],
  },
  {
    letter: 'S',
    coordinates: [
      [
        { x: 197, y: 43 },
        { x: 197, y: 43 },
        { x: 185, y: 39 },
        { x: 145, y: 36 },
        { x: 118, y: 45 },
        { x: 97, y: 74 },
        { x: 100, y: 112 },
        { x: 133, y: 123 },
        { x: 183, y: 125 },
        { x: 206, y: 135 },
        { x: 221, y: 162 },
        { x: 219, y: 215 },
        { x: 171, y: 248 },
        { x: 105, y: 232 },
        { x: 81, y: 220 },
      ],
    ],
  },
  {
    letter: 't',
    coordinates: [
      [
        { x: 136, y: 73 },
        { x: 136, y: 73 },
        { x: 139, y: 77 },
        { x: 147, y: 105 },
        { x: 149, y: 149 },
        { x: 149, y: 184 },
        { x: 149, y: 211 },
        { x: 153, y: 233 },
        { x: 171, y: 245 },
        { x: 189, y: 245 },
        { x: 197, y: 241 },
      ],
      [
        { x: 109, y: 153 },
        { x: 109, y: 153 },
        { x: 160, y: 151 },
        { x: 205, y: 149 },
      ],
    ],
  },
  {
    letter: 'T',
    coordinates: [
      [
        { x: 81, y: 81 },
        { x: 81, y: 81 },
        { x: 87, y: 81 },
        { x: 137, y: 81 },
        { x: 187, y: 81 },
        { x: 209, y: 81 },
        { x: 215, y: 81 },
      ],
      [
        { x: 149, y: 83 },
        { x: 149, y: 83 },
        { x: 149, y: 97 },
        { x: 149, y: 131 },
        { x: 151, y: 174 },
        { x: 151, y: 205 },
        { x: 151, y: 222 },
      ],
    ],
  },
  {
    letter: 'u',
    coordinates: [
      [
        { x: 109, y: 115 },
        { x: 109, y: 115 },
        { x: 109, y: 121 },
        { x: 111, y: 149 },
        { x: 113, y: 189 },
        { x: 117, y: 210 },
        { x: 129, y: 222 },
        { x: 150, y: 229 },
        { x: 177, y: 219 },
        { x: 191, y: 194 },
        { x: 197, y: 153 },
        { x: 199, y: 129 },
        { x: 199, y: 122 },
        { x: 199, y: 121 },
        { x: 201, y: 133 },
        { x: 203, y: 158 },
        { x: 207, y: 187 },
        { x: 213, y: 213 },
        { x: 217, y: 223 },
        {
          x: 219, y: 228,
        },
      ],
    ],
  },
  {
    letter: 'U',
    coordinates: [
      [
        { x: 93, y: 58 },
        { x: 93, y: 58 },
        { x: 95, y: 63 },
        { x: 97, y: 83 },
        { x: 102, y: 131 },
        { x: 107, y: 165 },
        { x: 113, y: 192 },
        { x: 123, y: 209 },
        { x: 141, y: 223 },
        { x: 169, y: 228 },
        { x: 194, y: 215 },
        { x: 207, y: 186 },
        { x: 206, y: 125 },
        { x: 200, y: 81 },
        { x: 199, y: 63 },
      ],
    ],
  },
  {
    letter: 'v',
    coordinates: [
      [
        { x: 97, y: 93 },
        { x: 97, y: 93 },
        { x: 105, y: 111 },
        { x: 121, y: 147 },
        { x: 139, y: 187 },
        { x: 145, y: 207 },
        { x: 150, y: 217 },
        { x: 153, y: 217 },
        { x: 162, y: 189 },
        { x: 171, y: 163 },
        { x: 183, y: 131 },
        { x: 194, y: 103 },
        { x: 203, y: 85 },
      ],
    ],
  },
  {
    letter: 'V',
    coordinates: [
      [
        { x: 87, y: 57 },
        { x: 87, y: 57 },
        { x: 94, y: 71 },
        { x: 105, y: 96 },
        { x: 123, y: 145 },
        { x: 138, y: 183 },
        { x: 146, y: 211 },
        { x: 149, y: 221 },
        { x: 151, y: 223 },
        { x: 161, y: 201 },
        { x: 173, y: 171 },
        { x: 189, y: 122 },
        { x: 202, y: 88 },
        { x: 211, y: 63 },
        { x: 216, y: 49 },
        { x: 219, y: 43 },
      ],
    ],
  },
  {
    letter: 'w',
    coordinates: [
      [
        { x: 73, y: 120 },
        { x: 73, y: 120 },
        { x: 77, y: 132 },
        { x: 87, y: 155 },
        { x: 99, y: 182 },
        { x: 107, y: 203 },
        { x: 111, y: 214 },
        { x: 113, y: 216 },
        { x: 119, y: 201 },
        { x: 130, y: 178 },
        { x: 138, y: 159 },
        { x: 143, y: 150 },
        { x: 145, y: 149 },
        { x: 149, y: 156 },
        { x: 161, y: 174 },
        { x: 173, y: 194 },
        { x: 180, y: 207 },
        { x: 183, y: 214 },
        { x: 185, y: 215 },
        { x: 192, y: 193 },
        { x: 205, y: 165 },
        { x: 215, y: 142 },
        { x: 221, y: 125 },
        {
          x: 225, y: 116,
        },
      ],
    ],
  },
  {
    letter: 'W',
    coordinates: [
      [
        { x: 29, y: 69 },
        { x: 29, y: 69 },
        { x: 43, y: 89 },
        { x: 68, y: 137 },
        { x: 94, y: 187 },
        { x: 105, y: 211 },
        { x: 111, y: 221 },
        { x: 120, y: 193 },
        { x: 129, y: 163 },
        { x: 139, y: 131 },
        { x: 145, y: 117 },
        { x: 152, y: 125 },
        { x: 169, y: 159 },
        { x: 179, y: 185 },
        { x: 189, y: 209 },
        { x: 196, y: 217 },
        { x: 209, y: 191 },
        { x: 225, y: 141 },
        { x: 244, y: 80 },
        { x: 253, y: 51 },
      ],
    ],
  },
  {
    letter: 'x',
    coordinates: [
      [
        { x: 111, y: 107 },
        { x: 111, y: 107 },
        { x: 115, y: 114 },
        { x: 137, y: 145 },
        { x: 167, y: 184 },
        { x: 185, y: 206 },
        {
          x: 199, y: 222,
        },
      ],
      [
        { x: 200, y: 95 },
        { x: 200, y: 95 },
        { x: 195, y: 103 },
        { x: 181, y: 127 },
        { x: 159, y: 164 },
        { x: 136, y: 201 },
        { x: 118, y: 232 },
      ],
    ],
  },
  {
    letter: 'X',
    coordinates: [
      [
        { x: 208, y: 41 },
        { x: 208, y: 41 },
        { x: 176, y: 99 },
        { x: 122, y: 201 },
        { x: 96, y: 245 },
      ],
      [
        { x: 95, y: 47 },
        { x: 95, y: 47 },
        { x: 114, y: 81 },
        { x: 173, y: 164 },
        {
          x: 226, y: 240,
        },
      ],
    ],
  },
  {
    letter: 'y',
    coordinates: [
      [
        { x: 111, y: 83 },
        { x: 111, y: 83 },
        { x: 110, y: 115 },
        { x: 115, y: 155 },
        { x: 129, y: 173 },
        { x: 157, y: 180 },
        { x: 179, y: 155 },
        { x: 188, y: 131 },
        { x: 191, y: 93 },
        { x: 191, y: 87 },
        { x: 193, y: 96 },
        { x: 197, y: 127 },
        { x: 205, y: 168 },
        { x: 212, y: 215 },
        { x: 207, y: 252 },
        { x: 172, y: 277 },
        { x: 119, y: 263 },
        {
          x: 114, y: 219,
        },
      ],
    ],
  },
  {
    letter: 'Y',
    coordinates: [
      [
        { x: 93, y: 46 },
        { x: 93, y: 46 },
        { x: 92, y: 52 },
        { x: 91, y: 73 },
        { x: 97, y: 99 },
        { x: 107, y: 121 },
        { x: 123, y: 139 },
        { x: 143, y: 148 },
        { x: 174, y: 147 },
        { x: 188, y: 132 },
        { x: 198, y: 111 },
        { x: 199, y: 68 },
        { x: 191, y: 45 },
      ],
      [
        { x: 159, y: 150 },
        { x: 159, y: 150 },
        { x: 157, y: 153 },
        { x: 157, y: 176 },
        { x: 158, y: 192 },
        { x: 157, y: 213 },
        {
          x: 157, y: 232,
        },
      ],
    ],
  },
  {
    letter: 'z',
    coordinates: [
      [
        { x: 113, y: 125 },
        { x: 113, y: 125 },
        { x: 114, y: 123 },
        { x: 135, y: 123 },
        { x: 165, y: 122 },
        { x: 181, y: 122 },
        { x: 187, y: 122 },
        { x: 187, y: 127 },
        { x: 178, y: 144 },
        { x: 161, y: 167 },
        { x: 128, y: 203 },
        { x: 118, y: 214 },
        { x: 111, y: 221 },
        { x: 108, y: 225 },
        { x: 112, y: 224 },
        { x: 133, y: 225 },
        { x: 165, y: 223 },
        { x: 189, y: 223 },
        { x: 197, y: 223 },
      ],
    ],
  },
  {
    letter: 'Z',
    coordinates: [
      [
        { x: 95, y: 74 },
        { x: 95, y: 74 },
        { x: 102, y: 75 },
        { x: 136, y: 75 },
        { x: 162, y: 75 },
        { x: 181, y: 73 },
        { x: 189, y: 74 },
        { x: 193, y: 75 },
        { x: 190, y: 77 },
        { x: 182, y: 90 },
        { x: 166, y: 113 },
        { x: 145, y: 142 },
        { x: 124, y: 171 },
        { x: 107, y: 196 },
        { x: 90, y: 215 },
        { x: 85, y: 220 },
        { x: 87, y: 222 },
        { x: 101, y: 223 },
        { x: 135, y: 223 },
        { x: 170, y: 222 },
        { x: 196, y: 221 },
        { x: 207, y: 223 },
      ],
    ],
  },
];

export const syllablesList: CreateSyllableDto[] = [
  {
    letter: 'a',
    syllables: [
      [ 'ar', 'pa' ],
      [ 'ar', 'di', 'lla' ],
      [ 'a', 'ni', 'llo' ],
    ],
  },
  {
    letter: 'b',
    syllables: [
      [ 'bi', 'ci', 'cle', 'ta' ],
      [ 'ba', 'lle', 'na' ],
      [ 'bar', 'co' ],
      [ 'bu', 'rro' ],
      [ 'bu', 'que' ],
    ],
  },
  {
    letter: 'c',
    syllables: [
      [ 'ca', 'mi', 'sa' ],
      [ 'ca', 'sa' ],
      [ 'ca', 'rro' ],
      [ 'co', 'ne', 'jo' ],
      [ 'co', 'co'],
      [ 'ca', 'ma'],
    ],
  },
  {
    letter: 'd',
    syllables: [
      [ 'de', 'do' ],
      [ 'da', 'do' ],
      [ 'dul', 'ce' ],
      [ 'di', 'no', 'sau', 'rio' ],
      [ 'di', 'ne', 'ro' ],
    ],
  },
  {
    letter: 'e',
    syllables: [
      [ 'e', 'le', 'fan', 'te' ],
      [ 'es', 'ca', 'le', 'ra' ],
      [ 'es', 'tre', 'lla' ],
      [ 'es', 'pe', 'jo' ],
    ],
  },
  {
    letter: 'f',
    syllables: [
      [ 'fue', 'go' ],
      [ 'fre', 'sa' ],
      [ 'fi', 'es', 'ta' ],
      [ 'fi', 'de', 'o' ],
      [ 'fru', 'ta' ],
    ],
  },
  {
    letter: 'g',
    syllables: [
      [ 'ga', 'to' ],
      [ 'ga', 'lle', 'ta' ],
      [ 'gui', 'ta', 'rra' ],
      [ 'ge', 'la', 'ti', 'na' ],
     ]},
  {
    letter: 'h',
    syllables: [
      [ 'hue', 'vo' ],
      [ 'hie', 'lo' ],
      [ 'hue', 'so' ],
      [ 'he', 'la', 'do' ],
    ],
  },
  {
    letter: 'i',
    syllables: [
      [ 'is', 'la' ],
      [ 'in', 'vier', 'no' ],
      [ 'in', 'dio' ],
      [ 'i', 'dio', 'ma' ],
    ],
  },
  {
    letter: 'j',
    syllables: [
      [ 'jue', 'go' ],
      [ 'ji', 'ra', 'fa' ],
      [ 'ju', 'gue', 'te' ],
      [ 'ju', 'go' ],
      [ 'ja', 'guar' ],
     ]},
  {
    letter: 'k',
    syllables: [
      [ 'ko', 'a', 'la' ],
      [ 'kios', 'co' ],
      [ 'ki', 'mo', 'no' ],
      [ 'ki', 'wi' ],
    ],
  },
  {
    letter: 'l',
    syllables: [
      [ 'lu', 'na' ],
      [ 'lo', 'bo' ],
      [ 'li', 'bro' ],
      [ 'lo', 'ro' ],
     ]},
  {
    letter: 'm',
    syllables: [
      [ 'mo', 'no' ],
      [ 'ma', 'no' ],
      [ 'mo', 'li', 'no' ],
      [ 'ma', 'pa' ],
      [ 'me', 'sa' ],
      [ 'ma', 'ri', 'po', 'sa' ],
    ]},
  {
    letter: 'n',
    syllables: [
      [ 'nu', 'be' ],
      [ 'ni', 'ño' ],
      [ 'na', 'riz' ],
      [ 'na', 've' ],
      [ 'no', 'che' ],
      [ 'nie', 've' ],
     ]},
  {
    letter: 'ñ',
    syllables: [
      [ 'ñan', 'du' ],
      [ 'pi', 'ña', 'ta' ],
      [ 'pi', 'ña' ],
    ],
  },
  {
    letter: 'o',
    syllables: [
      [ 'o', 've', 'ja' ],
      [ 'o', 're', 'ja' ],
      [ 'o', 'fi', 'ci', 'na' ],
    ],
  },
  {
    letter: 'p',
    syllables: [
      [ 'pal', 'me', 'ra' ],
      [ 'pe', 'lo', 'ta' ],
      [ 'pe', 'ra' ],
      [ 'pa', 'to' ],
      [ 'pa', 'ya', 'so' ],
    ],
  },
  {
    letter: 'q',
    syllables: [
      [ 'que', 'so' ],
      [ 'que', 'ru', 'bín' ],
      [ 'qui', 'mi', 'ca' ],
    ],
  },
  {
    letter: 'r',
    syllables: [
      [ 'ra', 'ma' ],
      [ 're', 'loj' ],
      [ 'ra', 'na' ],
      [ 'rue', 'da' ],
      [ 'ri', 'sa' ],
      [ 'ra', 'que', 'ta' ],
    ],
  },
  {
    letter: 's',
    syllables: [
      [ 'so', 'pa' ],
      [ 'si', 're', 'na' ],
      [ 'sa', 'po' ],
      [ 'som', 'bre', 'ro' ],
    ],
  },
  {
    letter: 't',
    syllables: [
      [ 'ta', 'za' ],
      [ 'tam', 'bor' ],
      [ 'ti', 'gre' ],
      [ 'te', 'ne', 'dor' ],
      [ 'to', 'ma', 'te' ],
      [ 'ti', 'je', 'ra' ],
    ],
  },
  {
    letter: 'u',
    syllables: [
      [ 'u', 'ni', 'ver', 'so' ],
      [ 'u', 'ni', 'for', 'me' ],
      [ 'u', 'ni', 'cor', 'nio' ],
    ],
  },
  {
    letter: 'v',
    syllables: [
      [ 'va', 'ca' ],
      [ 'ven', 'ta', 'na' ],
      [ 'va', 'cu', 'na' ],
      [ 've', 'la' ],
      [ 've', 'ra', 'no' ],
      [ 'ves', 'ti', 'do' ],
    ],
  },
  {
    letter: 'w',
    syllables: [
      [ 'wa', 'ffle' ],
      [ 'walk', 'man' ],
      [ 'wal', 'ter' ],
    ],
  },
  {
    letter: 'x',
    syllables: [
      [ 'ta', 'xi' ],
      [ 'bo', 'xe', 'a', 'dor' ],
    ],
  },
  {
    letter: 'y',
    syllables: [
      [ 'ye', 'so' ],
      [ 'ya', 'te' ],
      [ 'ye', 'ma' ],
      [ 'yo', 'gurt' ],
     ]},
  {
    letter: 'z',
    syllables: [
      [ 'za', 'pa', 'to' ],
      [ 'zo', 'rro' ],
      [ 'za', 'na', 'ho', 'ria' ],
    ],
  },
];

export const coursesList: CreateCourseDto[] = [
  {
    title:       'Lectura',
    subtitle:    'lectura',
    imageUrl:    'https://21hjk03hprzp3wb3op3limx7-wpengine.netdna-ssl.com/wp-content/uploads/2015/08/reading_1440765640.jpg',
    urlVideo:    'https://www.youtube.com/embed/DNQsGz5_R04?modestbranding=1&&iv_load_policy=3',
    description: 'Aprende los conceptos básico necesarios para aprender a leer.',
  },
  {
    title:       'Escritura',
    subtitle:    'escritura',
    imageUrl:    'https://www.curiosfera.com/wp-content/uploads/2017/11/so%C3%B1ar-con-escribir.jpg',
    urlVideo:    'https://www.youtube.com/embed/KyjjFYM8aUg?start=11',
    description: 'Aprender todo lo necesario para dominar el grandioso mundo de la escritura.',
  },
  {
    title:       'Matemáticas',
    subtitle:    'matematicas',
    imageUrl:    'https://i2.wp.com/www.calculators.org/graphics/algebra.jpg?zoom=2',
    urlVideo:    'https://www.youtube.com/embed/KyjjFYM8aUg?start=11',
    description: 'Domina las operaciones aritmética básicas y aprende como usarlos en la vida real.',
  },
  {
    title:       'Arte',
    subtitle:    'arte',
    imageUrl:    'http://digo.do/wp-content/uploads/2015/02/EL-ARTE-DE-DIBUJAR.jpg',
    urlVideo:    'https://www.youtube.com/embed/mfVahyqBmC8?start=7',
    description: 'Conoce todo lo que necesitas para convertirte en un gran artista del dibujo.',
  },
  {
    title:       'Programación',
    subtitle:    'programacion',
    imageUrl:    'https://www.educaciontrespuntocero.com/wp-content/uploads/2015/12/programacion-macbook-pixabay.jpg',
    urlVideo:    'https://www.youtube.com/embed/6svvtOjLA-A?start=6',
    description: 'Aprende todos lo conceptos básico que necesitas para iniciar el maravilloso arte de la proogramacion.',
  },
];

export const wordsList: CreateWordDto[] = [
  {
    letter: 'a',
    words: ['aguacate', 'avión', 'abeja', 'agua', 'anillo', 'arpa', 'ardilla'],
  },
  {
    letter: 'b',
    words: ['burro', 'bota', 'baile', 'biblia', 'ballena', 'barco', 'bicicleta'],
  },
  {
    letter: 'c',
    words: ['carro', 'camión', 'casa', 'conejo', 'coco', 'campana', 'caballo', 'cama'],
  },
  {
    letter: 'd',
    words: ['dado', 'delfín', 'duende', 'diamante', 'doctor', 'dedo', 'dulce'],
  },
  {
    letter: 'e',
    words: ['elefante', 'estrella', 'escalera', 'escoba', 'espejo', 'edificio', 'elote'],
  },
  {
    letter: 'f',
    words: ['Francia', 'fósforo', 'fuego', 'fruta', 'fresa', 'flor', 'flauta', 'fuente'],
  },
  {
    letter: 'g',
    words: ['gato', 'gusano', 'gallina', 'guante', 'guitarra', 'globo', 'gelatina', 'gorra'],
  },
  {
    letter: 'h',
    words: ['hilo', 'hielo', 'huevo', 'harina', 'hormiga', 'hueso', 'helado'],
  },
  {
    letter: 'i',
    words: ['iglesia', 'isla', 'iguana', 'iglú', 'imán', 'impresora', 'indio', 'idea'],
  },
  {
    letter: 'j',
    words: ['jaula', 'jarrón', 'jirafa', 'jugo', 'juguete', 'jabón', 'jaguar'],
  },
  {
    letter: 'k',
    words: ['koala', 'kiosco', 'kimono', 'kiwi', 'kilo', 'karate', 'karaoke'],
  },
  {
    letter: 'l',
    words: ['luna', 'lima', 'lago', 'lagarto', 'limón', 'lápiz', 'libro', 'lobo'],
  },
  {
    letter: 'm',
    words: ['mano', 'mesa', 'mapa', 'molino', 'mariposa', 'momia', 'mundo', 'medalla'],
  },
  {
    letter: 'n',
    words: ['naranja', 'niña', 'nave', 'nido', 'nube', 'nariz', 'niño'],
  },
  {
    letter: 'ñ',
    words: ['leña', 'moño', 'otoño', 'ñandú', 'piñata', 'ñoño'],
  },
  {
    letter: 'o',
    words: ['oso', 'oreja', 'olla', 'oveja', 'ojo', 'otoño', 'ola', 'oro'],
  },
  {
    letter: 'p',
    words: ['pera', 'pelota', 'pantalla', 'payaso', 'palmera', 'pato', 'paraguas'],
  },
  {
    letter: 'q',
    words: ['querer', 'quemar', 'querubín', 'queso', 'química'],
  },
  {
    letter: 'r',
    words: ['ratón', 'rosa', 'reloj', 'rueda', 'rana', 'raqueta', 'rey'],
  },
  {
    letter: 's',
    words: ['silla', 'sol', 'sombrilla', 'sapo', 'semáforo', 'sopa', 'serpiente', 'sombrero'],
  },
  {
    letter: 't',
    words: ['taza', 'tambor', 'tigre', 'tenedor', 'teléfono', 'taxi', 'tijera', 'tomate'],
  },
  {
    letter: 'u',
    words: ['uvas', 'uno', 'unicornio', 'universo', 'uniforme', 'uña', 'urbano'],
  },
  {
    letter: 'v',
    words: ['vaca', 'vela', 'ventana', 'viento', 'vino', 'volcán', 'vaso', 'vestido'],
  },
  {
    letter: 'w',
    words: ['waffle', 'Walter', 'walkman', 'webcam', 'waterpolo'],
  },
  {
    letter: 'x',
    words: ['xilófono', 'saxofón', 'taxi', 'éxito', 'boxeador'],
  },
  {
    letter: 'y',
    words: ['yoyo', 'yeso', 'yate', 'yema', 'yunque', 'yogurt'],
  },
  {
    letter: 'z',
    words: ['zapato', 'zapote', 'zorro', 'zanahoria', 'zoológico', 'zapatilla'],
  },
];

export const letters: CreateLetterDto = {

  vocals:       'aeiou',
  alphabet:     'abcdefghijklmnñopqrstuvwxyz',
  consonants:   'bcdfghjklmnñpqrstvwxyz',
  combinations: [
    {
      letter: 'a',
      combinations: [
        { w: 'aa', p: 'aa' },
        { w: 'ae', p: 'ae' },
        { w: 'ai', p: 'ai' },
        { w: 'ao', p: 'ao' },
        { w: 'au', p: 'au' },
      ],
    },
    {
      letter: 'b',
      combinations: [
        { w: 'ba', p: 'ba' },
        { w: 'be', p: 've' },
        { w: 'bi', p: 'bi' },
        { w: 'bo', p: 'bo' },
        { w: 'bu', p: 'bu' },
      ],
    },
    {
      letter: 'c',
      combinations: [
        { w: 'ca', p: 'ca' },
        { w: 'ce', p: 'ce' },
        { w: 'ci', p: 'ci' },
        { w: 'co', p: 'co' },
        { w: 'cu', p: 'cu' },
      ],
    },
    {
      letter: 'd',
      combinations: [
        { w: 'da', p: 'da' },
        { w: 'de', p: 'de' },
        { w: 'di', p: 'di' },
        { w: 'do', p: 'do' },
        { w: 'du', p: 'du' },
      ],
    },
    {
      letter: 'e',
      combinations: [
        { w: 'ea', p: 'ea' },
        { w: 'ee', p: 'ee' },
        { w: 'ei', p: 'ei' },
        { w: 'eo', p: 'eo' },
        { w: 'eu', p: 'eu' },
      ],
    },
    {
      letter: 'f',
      combinations: [
        { w: 'fa', p: 'fa' },
        { w: 'fe', p: 'fe' },
        { w: 'fi', p: 'fi' },
        { w: 'fo', p: 'fo' },
        { w: 'fu', p: 'fu' },
      ],
    },
    {
      letter: 'g',
      combinations: [
        { w: 'ga', p: 'ga' },
        { w: 'gue', p: 'gue' },
        { w: 'gui', p: 'gui' },
        { w: 'go', p: 'go' },
        { w: 'gu', p: 'gu' },
        { w: 'ge', p: 'ge' },
        { w: 'gi', p: 'ji' },

      ],
    },
    {
      letter: 'h',
      combinations: [
        { w: 'ha', p: 'a' },
        { w: 'he', p: 'e' },
        { w: 'hi', p: 'i' },
        { w: 'ho', p: 'o' },
        { w: 'hu', p: 'u' },
      ],
    },
    {
      letter: 'i',
      combinations: [
        { w: 'ia', p: 'ia' },
        { w: 'ie', p: 'ie' },
        { w: 'ii', p: 'ii' },
        { w: 'io', p: 'io' },
        { w: 'iu', p: 'iu' },
      ],
    },
    {
      letter: 'j',
      combinations: [
        { w: 'ja', p: 'ja' },
        { w: 'je', p: 'ge' },
        { w: 'ji', p: 'ji' },
        { w: 'jo', p: 'ho' },
        { w: 'ju', p: 'ju' },
      ],
    },
    {
      letter: 'k',
      combinations: [
        { w: 'ka', p: 'ka' },
        { w: 'ke', p: 'ke' },
        { w: 'ki', p: 'ki' },
        { w: 'ko', p: 'ko' },
        { w: 'ku', p: 'ku' },
      ],
    },
    {
      letter: 'l',
      combinations: [
        { w: 'la', p: 'la' },
        { w: 'le', p: 'le' },
        { w: 'li', p: 'li' },
        { w: 'lo', p: 'lo' },
        { w: 'lu', p: 'lu' },
      ],
    },
    {
      letter: 'm',
      combinations: [
        { w: 'ma', p: 'ma' },
        { w: 'me', p: 'me' },
        { w: 'mi', p: 'mi' },
        { w: 'mo', p: 'mo' },
        { w: 'mu', p: 'mu' },
      ],
    },
    {
      letter: 'n',
      combinations: [
        { w: 'na', p: 'na' },
        { w: 'ne', p: 'ne' },
        { w: 'ni', p: 'ni' },
        { w: 'no', p: 'no' },
        { w: 'nu', p: '.. nu' },
      ],
    },
    {
      letter: 'ñ',
      combinations: [
        { w: 'ña', p: 'ña' },
        { w: 'ñe', p: 'ñe' },
        { w: 'ñi', p: 'ñi' },
        { w: 'ño', p: 'ño' },
        { w: 'ñu', p: 'ñu' },
      ],
    },
    {
      letter: 'o',
      combinations: [
        { w: 'oa', p: 'oa' },
        { w: 'oe', p: 'oe' },
        { w: 'oi', p: 'oi' },
        { w: 'oo', p: 'oo' },
        { w: 'ou', p: 'ou' },
      ],
    },
    {
      letter: 'p',
      combinations: [
        { w: 'pa', p: 'pa' },
        { w: 'pe', p: 'pe' },
        { w: 'pi', p: 'pi' },
        { w: 'po', p: 'po' },
        { w: 'pu', p: 'pu' },
      ],
    },
    {
      letter: 'q',
      combinations: [
        { w: 'que', p: 'que' },
        { w: 'qui', p: 'qui' },
      ],
    },
    {
      letter: 'r',
      combinations: [
        { w: 'ra', p: 'ra' },
        { w: 're', p: 're' },
        { w: 'ri', p: 'ri' },
        { w: 'ro', p: 'ro' },
        { w: 'ru', p: 'ru' },
      ],
    },
    {
      letter: 's',
      combinations: [
        { w: 'sa', p: 'sa' },
        { w: 'se', p: 'se' },
        { w: 'si', p: 'si' },
        { w: 'so', p: 'so' },
        { w: 'su', p: 'su' },
      ],
    },
    {
      letter: 't',
      combinations: [
        { w: 'ta', p: 'ta' },
        { w: 'te', p: 'te' },
        { w: 'ti', p: '.. tii' },
        { w: 'to', p: '.. tow' },
        { w: 'tu', p: 'tu' },
      ],
    },
    {
      letter: 'u',
      combinations: [
        { w: 'ua', p: '.. uha' },
        { w: 'ue', p: '.. uhe' },
        { w: 'ui', p: '.. uy' },
        { w: 'uo', p: 'uo' },
        { w: 'uu', p: 'u, u' },
      ],
    },
    {
      letter: 'v',
      combinations: [
        { w: 'va', p: 'va' },
        { w: 've', p: 've' },
        { w: 'vi', p: 'vi' },
        { w: 'vo', p: 'vo' },
        { w: 'vu', p: 'vu' },
      ],
    },
    {
      letter: 'w',
      combinations: [
        { w: 'wa', p: 'wa' },
        { w: 'we', p: 'we' },
        { w: 'wi', p: 'wi' },
        { w: 'wo', p: 'wo' },
        { w: 'wu', p: 'wu' },
      ],
    },
    {
      letter: 'x',
      combinations: [
        { w: 'xa', p: 'xa' },
        { w: 'xe', p: 'xe' },
        { w: 'xi', p: 'xi' },
        { w: 'xo', p: 'so' },
        { w: 'xu', p: 'xu' },
      ],
    },
    {
      letter: 'y',
      combinations: [
        { w: 'ya', p: 'ya' },
        { w: 'ye', p: '.. ihe' },
        { w: 'yi', p: 'yi' },
        { w: 'yo', p: 'yo' },
        { w: 'yu', p: 'yu' },
      ],
    },
    {
      letter: 'z',
      combinations: [
        { w: 'za', p: 'za' },
        { w: 'ze', p: 'ze' },
        { w: 'zi', p: 'zi' },
        { w: 'zo', p: 'zo' },
        { w: 'zu', p: 'zu' },
      ],
    },

  ],
  letterSounds: [
    { letter: 'a', sound: '"ha"'    },
    { letter: 'á', sound: '"ha"'    },
    { letter: 'b', sound: '"b"'     },
    { letter: 'c', sound: '"ce"'    },
    { letter: 'd', sound: '"d"'     },
    { letter: 'e', sound: '"e"'     },
    { letter: 'é', sound: '"e"'     },
    { letter: 'f', sound: '"f"'     },
    { letter: 'g', sound: '"ge"'    },
    { letter: 'h', sound: '"ache"'  },
    { letter: 'i', sound: '"i"'     },
    { letter: 'í', sound: '"i"'     },
    { letter: 'j', sound: '...jota' },
    { letter: 'k', sound: '"ka"'    },
    { letter: 'l', sound: 'l'       },
    { letter: 'm', sound: '"eme"'   },
    { letter: 'n', sound: '"ene"'   },
    { letter: 'ñ', sound: '"eñe"'   },
    { letter: 'o', sound: '"oh"'    },
    { letter: 'ó', sound: '"oh"'    },
    { letter: 'p', sound: '.. p'    },
    { letter: 'q', sound: '"cu"'    },
    { letter: 'r', sound: '"erre"'  },
    { letter: 's', sound: '"ese"'   },
    { letter: 't', sound: '.. te'   },
    { letter: 'u', sound: '"u .."'  },
    { letter: 'ú', sound: '"u .."'  },
    { letter: 'v', sound: '"uve"'   },
    { letter: 'w', sound: '"doble ve"' },
    { letter: 'x', sound: '".. equis"' },
    { letter: 'y', sound: 'ye ..'      },
    { letter: 'z', sound: 'seta'       },
  ],

};
